import { QueryProvider } from "../providers";
import "../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="mx-auto justify-center max-w-xl flex-col">
      <QueryProvider>{children}</QueryProvider>
    </main>
  );
}
